version: '3.4'

services:
  workflowengine:
    image: workflow-engine
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
